webtalk_init -webtalk_dir C:\\Users\\Sofs\\Documents\\CR\\tp7\\tp7.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-06-06 20:03:42" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a5sl8epduk4io7ahknjc0n9gio" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2400G with Radeon Vega Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.982 GB" -context "user_environment"
webtalk_add_data -client project -key date_generated -value "2018-06-06 20:03:33" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "l4qr115juojjte6p1vk23gar4p" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2400G with Radeon Vega Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.982 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1528309983841" -context "sdk\\\\bsp/1528309983841"
webtalk_add_data -client sdk -key hwid -value "1524169037444" -context "sdk\\\\bsp/1528309983841"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1528309983841"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1528309983841"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1528309983841"
webtalk_add_data -client sdk -key uid -value "1528310003438" -context "sdk\\\\application/1528310003438"
webtalk_add_data -client sdk -key hwid -value "1524169037444" -context "sdk\\\\application/1528310003438"
webtalk_add_data -client sdk -key bspid -value "1528309983841" -context "sdk\\\\application/1528310003438"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1528310003438"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1528310003438"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1528310003438"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1528310003438"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1528310003438"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1528310003438"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1528311813644"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1528311813644"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1528311813644"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1528311813644"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1528311813644"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1528311813644"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1528311813644"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1528311813644"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1528311822466"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1528311822466"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1528311822466"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1528311822466"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1528311822466"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1528311822466"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1528311822466"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1528311822466"
webtalk_transmit -clientid 552731273 -regid "" -xml C:\\Users\\Sofs\\Documents\\CR\\tp7\\tp7.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Sofs\\Documents\\CR\\tp7\\tp7.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Sofs\\Documents\\CR\\tp7\\tp7.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
